export const Types = {
    /*SEARCHBARVISIBLE : "SEARCHBARVISIBLE",
    CHANGEURI : "CHANGEURI",*/
    CHANGEITEMUSER: "CHANGEITEMUSER",
    CHANGEITEMPOST: "CHANGEITEMPOST",
    SIGN_IN: "SIGN_IN",
    RESTORE_TOKEN: "RESTORE_TOKEN"
}

